### ISSUE TITLE
有考虑过使用Deno吗

### ISSUE THREAD

**Issue by Aloento** [Vibing/react-admin#2]
大佬，我在使用你的这个预建包，近期发现了Deno这个玩意，不过我有点研究不懂，不知道大佬有没有什么方法把这玩意迁移到Deno去，这样构建的速度或许会更快？

**Comment by chenlong-io** [comment]
@Aloento 目前好像没有Deno写的前端构建工具，目前最主流的仍是 webpack，或者 vite 也不错
